language: r
pandoc_version: 1.16

sudo: required

addons:
  apt:
    packages:
      - libxml2-dev

os:
    - linux
    - osx

r_packages:
    - rmarkdown

r_github_packages:
    - jimhester/covr

after_success:
    - Rscript -e 'library(covr);codecov()'

notifications:
    email:
      recipients:
          - alexthompson1991@hotmail.com
      on_success: change
      on_failure: always
