technical_indicator_specification <- list(
  sma = list(required = c("time_period", "series_type"), optional = c()),
  ema = list(required = c("time_period", "series_type"), optional = c()),
  wma = list(required = c("time_period", "series_type"), optional = c()),
  dema = list(required = c("time_period", "series_type"), optional = c()),
  tema = list(required = c("time_period", "series_type"), optional = c()),
  trima = list(required = c("time_period", "series_type"), optional = c()),
  kama = list(required = c("time_period", "series_type"), optional = c()),
  mama = list(required = "series_type", optional = c("fastlimit", "slowlimit")),
  t3 = list(required = c("time_period", "series_type"), optional = c()),
  macd = list(required = "series_type", optional = c("fastperiod", "slowperiod", "signalperiod")),
  macdext = list(required =  "series_type", optional = c("fastperiod", "slowperiod", "signalperiod", "fastmatype", "slowmatype", "signalmatype")),
  stoch = list(required = c(), optional = c("fastkperiod", "slowkperiod", "slowdperiod", "slowkmatype", "slowdmatype")),
  stochf = list(required = c(), optional = c("fastkperiod", "fastdperiod", "fastdmatype")),
  rsi = list(required = c("time_period", "series_type"), optional = c()),
  stochrsi = list(required = c("time_period", "series_type"), optional = c("fastkperiod", "fastdperiod", "fastdmatype")),
  willr = list(required = "time_period", optional = c()),
  adx = list(required = "time_period", optional = c()),
  adxr = list(required = "time_period", optional = c()),
  apo = list(required = "series_type", optional = c("fastperiod", "slowperiod", "matype")),
  ppo = list(required = "series_type", optional = c("fastperiod", "slowperiod", "matype")),
  mom = list(required = c("time_period", "series_type"), optional = c()),
  cci = list(required = "time_period", optional = c()),
  cmo = list(required = c("time_period", "series_type"), optional = c()),
  roc = list(required = c("time_period", "series_type"), optional = c()),
  rocr = list(required = c("time_period", "series_type"), optional = c()),
  aroon = list(required = c("time_period"), optional = c()),
  aroonosc = list(required = "time_period", optional = c()),
  mfi = list(required = "time_period", optional = c()),
  trix = list(required = c("time_period", "series_type"), optional = c()),
  ultosc = list(required = c(), optional = c("timeperiod1", "timeperiod2", "timeperiod3")),
  dx = list(required = "time_period", optional = c()),
  minus_di = list(required = "time_period", optional = c()),
  plus_di = list(required = "time_period", optional = c()),
  minus_dm = list(required = "time_period", optional = c()),
  plus_dm = list(required = "time_period", optional = c()),
  bbands = list(required = c("time_period", "series_type"), optional = c("nbdevup", "nbdevdn", "matype")),
  midpoint = list(required = c("time_period", "series_type"), optional = c()),
  midprice = list(required = "time_period", optional = c()),
  sar = list(required = c(), optional = c("acceleration", "maximum")),
  atr = list(required = "time_period", optional = c()),
  natr = list(required = "time_period", optional = c()),
  adosc = list(required = c(), optional = c("fastperiod", "slowperiod")),
  ht_trendline = list(required = "series_type", optional = c()),
  ht_sine = list(required = "series_type", optional = c()),
  ht_trendmode = list(required = "series_type", optional = c()),
  ht_dcperiod = list(required = "series_type", optional = c()),
  ht_dcphase = list(required = "series_type", optional = c()),
  ht_phasor = list(required = "series_type", optional = c())
)


